### ISSUE TITLE
Add a way to include custom HTTP headers to request

### ISSUE THREAD

**Issue by BojanOro** [jobtoday/react-native-image-viewing#10]
When making a request to download an image that requires authentication, it would be nice to be able to provide additional authentication headers so the request can be successfully processed..

**Comment by antonKalinin** [comment]
Hey @BojanOro if I understand correctly your case then this ability is already available: ImageView component accepts array of image sources. So you can pass authorisation headers next way:

`<ImageView
  images={[
    {
       uri: 'example.com/yourimage',
       headers: {
          'Authorization': 'your_auth_header'
       }
    }
  ]}
  ...
/>;`

Could you please check it and if its okay, I will close the issue.

**Comment by BojanOro** [comment]
Ah, I could not find this capability in the documentation. Thanks!
