### ISSUE TITLE
[Critical Bug!] Very sluggish behavior on Android only (works perfect on iOS)

### ISSUE THREAD

**Issue by karanmartian** [jobtoday/react-native-image-viewing#119]
Works very well on ios but not on android, it feels like its stuck and sluggish on android. u have to try really hard to zoom in and keep pinching and then if you are lucky it zooms very little on android. On ios its perfect, so fluid. This is a critical bug! Even in the demo shown by developer, hes shown it working on iOS, did he ever try this on Android one can question.

**Comment by moshangqi** [comment]
+1，这个在android有重大问题

**Comment by jake-stewart** [comment]
+1

**Comment by eeshaan** [comment]
+1

**Comment by bjornhutter** [comment]
@karanmartian Temporary fix for this is to set swipeToCloseEnabled={false} on Android e.g.

`swipeToCloseEnabled={Platform.OS === 'ios'}`

It makes pinch to zoom work much better on Android but you won't be able to close the modal on swipe up/down.

**Comment by AlexCernik** [comment]
+1

**Comment by orhangazi** [comment]
+1

**Comment by antonKalinin** [comment]
Closing for now due to fix done in v.0.2.2

**Comment by orhangazi** [comment]
I tried with v0.2.2 but it is doesn't fixed. I need use `swipeToCloseEnabled={Platform.OS === 'ios'}` still.
