### ISSUE TITLE
Close button on modal disappears when zooming

### ISSUE THREAD

**Issue by gavinangym** [jobtoday/react-native-image-viewing#14]
The modal close button disappears when zooming, and I can't seem to dismiss the modal unless I reset the zoom to the original size.

Is there a way to keep the X button always visible while zooming?

**Comment by antonKalinin** [comment]
Hi @gavinangym, it's done by purpose but I think we will add prop to disable it in future.

**Comment by hugopretorius914** [comment]
@antonKalinin a custom close component and the above-mentioned prop would be amazing! Can we please? ❤️🤸🏻‍♂️🙌🏻🌈
