### ISSUE TITLE
How to determine current page?

### ISSUE THREAD

**Issue by JanErikFoss** [jobtoday/react-native-image-viewing#17]
I need to know which image is currently showing on the screen.

Is that possible if I just let the user scroll?

As far as I can tell I need to manually update the currentIndex value, but I have no way of knowing when or where the user has scrolled to.

**Comment by antonKalinin** [comment]
@JanErikFoss Hey! Just added `onImageIndexChange` prop to enable tracking that image has changed, please update to v0.1.6
