### ISSUE TITLE
Bundling failed - `main` module field that could not be resolved

### ISSUE THREAD

**Issue by riordanpawley** [jobtoday/react-native-image-viewing#18]
Latest release caused this in bundler. Reverting to 0.1.3 fixed the issue immediately.
While trying to resolve module `react-native-image-viewing` from file `/Users/.../src/screens/image-list/ImageDetailsPickerScreen.tsx`, the package `/Users/.../node_modules/react-native-image-viewing/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/Users/.../node_modules/react-native-image-viewing/dist/index.js`. Indeed, none of these files exist:

**Comment by punisher97** [comment]
Please build typescript, missing dist folder

Thanks

**Comment by antonKalinin** [comment]
@riordanpawley @punisher97 Done, sorry for that. v0.1.5
