### ISSUE TITLE
Pinch to zoom is not working

### ISSUE THREAD

**Issue by TylerPin** [jobtoday/react-native-image-viewing#24]
Pinch to zoom feature is not working for me, tested on Android.

**Comment by maksimko** [comment]
@TylerPin Can you please tell 

- Android OS version
- device model
- this lib version

Thanks.

**Comment by TylerPin** [comment]
Sorry, nested the library inside modal which cause pinch to zoom not functioning

**Comment by Pavaneshpratap** [comment]
> Sorry, nested the library inside modal which cause pinch to zoom not functioning

then how can wen use this library inside the modal with pinch to zoom functioning ?
