### ISSUE TITLE
Android Modal Problem

### ISSUE THREAD

**Issue by alimert801** [jobtoday/react-native-image-viewing#34]
Hi,

I just tried react-native-image-viewing. It work very well. Also performance is awesome. But I have problem for android. IOS doesn't have that problem. It work well. Problem is that Modal doesn't bring to front.Like below screenshot:

![Android](https://user-images.githubusercontent.com/46167741/76595164-47a84380-64fb-11ea-8ad1-2f38630bb513.jpeg)

How can I solve?

**Comment by methineeinkan** [comment]
+1

**Comment by Willt123** [comment]
Hey this look like an issue with the Modal.android.js file.

As a patch you could try removing this line: 
`top: StatusBar.currentHeight`

If I have time I'll try and create a PR.

**Comment by methineeinkan** [comment]
As a patch you could try removing this line:
top: StatusBar.currentHeight 
Not work

**Comment by Willt123** [comment]
@methineeinkan 

Hey if your issue is the same as the one here it could be that your are rendering the
`<ImageView>`
Component at a higher level.

I had to make sure I was rendering it outside my Baselayout in order to get it to properly fill the screen over the top of the Bottom tab navigator.

**Comment by AlishahSolanki** [comment]
I have also encountered the same issue, in which my navigation bar wasn't hiding...
Modal.android.js is buggy ... easy fix just replace code with react-native default model which handles everything.
![Screenshot 2020-04-01 at 4 14 14 PM](https://user-images.githubusercontent.com/18504965/78131071-daba0680-7433-11ea-9e6a-66051ba047e4.png)

@Willt123 @alimert801 @methineeinkan @antonKalinin @maksimko @globchastyy 
try this ...
before:
![Screenshot_1585739939](https://user-images.githubusercontent.com/18504965/78131601-c62a3e00-7434-11ea-976a-014dc1c5c9a3.png)

after:
![Screenshot_1585739998](https://user-images.githubusercontent.com/18504965/78131630-d2160000-7434-11ea-863e-f02aa873c253.png)

**Comment by alimert801** [comment]
@AlishahSolanki Thank you for your solution, this fixed my problem. But, When I do that solution, I can't pinch to zoom. It doesn't work.

**Comment by AlishahSolanki** [comment]
@alimert801 yes, I have tested pinch-zoom not working only tap to zoom works...
once I find a fix i'll post it here.

**Comment by gerryfletch** [comment]
@AlishahSolanki Thanks for taking a look into this, looking forward to a solution. Hope we can get a PR through

**Comment by cybercoder** [comment]
It is like this inside stack in ```android```:
![Screen Shot 2020-04-24 at 19 05 50](https://user-images.githubusercontent.com/437872/80224282-bc27e380-865e-11ea-92c6-554bc93fb637.png)

But it is normal in ```ios```

```javascript

  return (
    <>
      <ImageViewer
        images={files.map((f) => ({uri: f.path}))}
        imageIndex={viewingIndex}
        visible={ImageViwerIsVisible}
        onRequestClose={() => showImageViwer(false)}
      />
      <View
        style={{
          flexDirection: 'row',
          flex: 1,
          padding: 10,
          alignItems: 'center',
        }}>
               ....
        </View>
     </>
)```

**Comment by lkakada** [comment]
I had the same issue when i used the modal. I cannot pinch-zoom. Any solution?

**Comment by anandhakumarpalanisamy** [comment]
> It is like this inside stack in `android`:
> ![Screen Shot 2020-04-24 at 19 05 50](https://user-images.githubusercontent.com/437872/80224282-bc27e380-865e-11ea-92c6-554bc93fb637.png)
> 
> But it is normal in `ios`
> 
> ```js
>   return (
>     <>
>       <ImageViewer
>         images={files.map((f) => ({uri: f.path}))}
>         imageIndex={viewingIndex}
>         visible={ImageViwerIsVisible}
>         onRequestClose={() => showImageViwer(false)}
>       />
>       <View
>         style={{
>           flexDirection: 'row',
>           flex: 1,
>           padding: 10,
>           alignItems: 'center',
>         }}>
>                ....
>         </View>
>      </>
> )```
> ```



Try this . This worked for me . 

- **Set the height for main view wrapper of the component's render method() to 100 %**

- **keep image viewer as the first view component in the component's render() method**

- **Set presentationStyle = {"overFullScreen"}** - This is the recommended settings for Android.

**Example:**
```
 render() {

**Set the height for main view wrapper of the component render method() to 100 %**
  <View style={{backgroundColor:'white',height:'100%'}}>

        **keep image viewer as the first view component in the component's render() method**
        <ImageView
            images={[
              {
                 uri : (this.state.pickedImage)?this.state.pickedImage.uri:[],
              },
            ]}
            imageIndex={0}
            swipeToCloseEnabled={false}
            presentationStyle = {"overFullScreen"}
            visible={this.state.isProfilePicImageViewVisible}
            onRequestClose={() => this.pickProfilePicImageCloseHandler()}
            />

        // Other view components
        // Other view components

   </View>

 }
```

**Comment by anandhakumarpalanisamy** [comment]
> I had the same issue when i used the modal. I cannot pinch-zoom. Any solution?

**Try setting swipeToCloseEnabled to false** 

> swipeToCloseEnabled={false}



Pinch Zoom is working for me after that . 
I think if "swipeToCloseEnabled is true", it is confused between swipe gesture and pinch zoom gesture. Pinch zoom was not working in that scenario

**Comment by anandhakumarpalanisamy** [comment]
> @AlishahSolanki Thank you for your solution, this fixed my problem. But, When I do that solution, I can't pinch to zoom. It doesn't work.

**Try setting swipeToCloseEnabled to false**

> swipeToCloseEnabled={false}

Pinch Zoom is working for me after that .

I think if "swipeToCloseEnabled is true", it is confused between swipe gesture and pinch zoom gesture. Pinch zoom was not working in that scenario

**Comment by alimert801** [comment]
@anandhakumarpalanisamy I tried your solution but for my app, pinch zoom still doesn't work.

**Comment by antonKalinin** [comment]
We have replaced custom modal implementation with RN `Modal` component, please check v0.2.0. Going to close this issue, feel free to reopen if problems still occur.
