### ISSUE TITLE
Loading local images

### ISSUE THREAD

**Issue by OrekuD** [jobtoday/react-native-image-viewing#38]
When using the require tag to load images, image viewer breaks

**Comment by pwin519** [comment]
I have the same question, the error message is: [Error: Cannot get the size of an image for an empty URI]

**Comment by GoktuqCan** [comment]
> I have the same question, the error message is: [Error: Cannot get the size of an image for an empty URI]

I am also having this error.

**Comment by antonKalinin** [comment]
Should work in v0.2.0.

**Comment by Maoravitan** [comment]
still not working.

**Comment by vapstor** [comment]
true:
`useEffect(() => {
        console.log("useEffect!")
    })

    const imagesSourceLocal = [
        {
            uri: require("./../../../assets/imageSamples/image01.jpg")
        }
    ]

    const [currentImageIndex, setImageIndex] = useState(0);
    const [images, setImages] = useState(imagesSourceLocal);
    const [isVisible, setIsVisible] = useState(false);

    const onSelect = (index) => {
        setImageIndex(index);
        setIsVisible(true);
    };
`

...

`<ImageView
                images={images}
                imageIndex={currentImageIndex}
                visible={isVisible}
                presentationStyle="overFullScreen"
                onRequestClose={() => setIsVisible(false)}
            />`

Error: `Value for uri cannot be cast from Double to String`

**Comment by jharrisGitHub** [comment]
Don't use the object structure and **'uri'**:

**Ex:**
const imagesSourceLocal = [
        require("./../../../assets/imageSamples/image01.jpg"),
]
