### ISSUE TITLE
Add double tap to zoom feature

### ISSUE THREAD

**Issue by antonKalinin** [jobtoday/react-native-image-viewing#4]

**Comment by antonKalinin** [comment]
Added for android in v0.1.2

**Comment by OlaAde** [comment]
Hi, just tried the library. But both pinch to zoom and double tap does not work.

**Comment by sensoft2207** [comment]
Same issue double tap and pinch to zoom in/out not working for android and IOS in RN v 0.60.4.
Any solution?

**Comment by antonKalinin** [comment]
@OlaAde @alt332 @sensoft2207 you are right guys, thanks! After migration to TS easily forgot that publishing new version now requires one more step: building :) 

Android: Pinch zoom and double tap to zoom should be fine in v0.1.3
iOS: pinch zoom should work even in v0.1.2 + double tap to zoom is in progress and thats why this issue is not closed yet.

Thanks for reporting.

**Comment by OlaAde** [comment]
Hi @antonKalinin , I just tried the newly published version. Yes, the zooming is stable. Thanks

**Comment by antonKalinin** [comment]
Double tap to zoom for iOS finally landed in v0.1.4

**Comment by joshjens** [comment]
first, thanks for such a great little utility! second. i just upgraded hoping for ios double tap zoom (has been working fine in android), and it still doesn't seem to work. any ideas?
