### ISSUE TITLE
Swiping up to close can lead to a screen with no image.

### ISSUE THREAD

**Issue by galziv** [jobtoday/react-native-image-viewing#41]
When swiping up to close the the preview, if not sliding all the way to the top, the image disappears from the screen but the preview stays open.
![image](https://user-images.githubusercontent.com/8125123/81477744-fcbc5b00-9221-11ea-8b3f-0c6eb517789a.png)

**Comment by antonKalinin** [comment]
Should be better in [v0.2.0](https://github.com/jobtoday/react-native-image-viewing/releases/tag/v0.2.0)
