### ISSUE TITLE
Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. 

### ISSUE THREAD

**Issue by anandhakumarpalanisamy** [jobtoday/react-native-image-viewing#42]
**Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.**

**Issue Video**

![error](https://user-images.githubusercontent.com/30879156/81809200-3ee6e480-9521-11ea-9ac3-13ec9b12e024.gif)

**Findings :**

The **onRequestClose** handler associated with the device's back button press  is **not aborting after the component gets unmounted and navigated to a new page**

![error2](https://user-images.githubusercontent.com/30879156/81810283-f6302b00-9522-11ea-88ef-b32cbacdbb16.gif)

**Comment by antonKalinin** [comment]
Should be fine in v0.2.0

**Comment by lively-krishnan** [comment]
此问题依然存在，我使用的版本是 0.2.2
