### ISSUE TITLE
TouchOpacity don not working in FooterComponent

### ISSUE THREAD

**Issue by minhChien98** [jobtoday/react-native-image-viewing#68]
In the FooterComponent, I have TouchOpacity component and i can not onPress in TouchOpacity
Thanks for great library.

**Comment by ahmetbicer** [comment]
You are probably importing TouchableOpacity from `react-native-gesture-handler`. Import it from `react-native`. It should fix the issue.

**Comment by minhChien98** [comment]
i am importing it form _react-native_.  @ahmetbicer

**Comment by ahmetbicer** [comment]
I was having the same issue when i import it from `react-native-gesture-handler`. I thought it is the same issue. Sorry

**Comment by minhChien98** [comment]
Can you show me that code you write?
Thanks! @ahmetbicer

**Comment by ahmetbicer** [comment]
```
import { View, TouchableNativeFeedback } from 'react-native';
...

footerComponent = () => (
    <View style={styles.saveButton}>
        <TouchableNativeFeedback delayPressIn={0} background={TouchableNativeFeedback.Ripple('#150344', true)} onPress={this.saveImage}>
          <View style={styles.saveButton}>
            <Icon color="#150344" size={28} name="content-save" />
            <Subheading style={{ marginLeft: 8 }}>Save</Subheading>
          </View>
        </TouchableNativeFeedback>
      </View>
  )
```

I am using TouchableNativeFeedback but TouchableOpacity is working too. There are some nested views because i was trying to achieve ripple effect in button boundaries.
