### ISSUE TITLE
How to display image name at top

### ISSUE THREAD

**Issue by sandeepg1220** [jobtoday/react-native-image-viewing#70]
Need the image name for display

**Comment by antonKalinin** [comment]
Hey @sandeepg1220, you can custom `HeaderComponent` which will receive current image index each time you swipe an image, so then you can find image name by the index and display in header. Something like following:

`
import ImageView from "react-native-image-viewing";

const images = [
  {
    title: "First image",
    uri: "https://images.unsplash.com/photo-1571501679680-de32f1e7aad4",
  },
  {
    title: "Second image",
    uri: "https://images.unsplash.com/photo-1573273787173-0eb81a833b34",
  },
  {
    title: "Third image",
    uri: "https://images.unsplash.com/photo-1569569970363-df7b6160d111",
  },
];

const [visible, setIsVisible] = useState(false);

<ImageView
  images={images}
  imageIndex={0}
  visible={visible}
  onRequestClose={() => setIsVisible(false)}
  HeaderComponent={({imageIndex}) => <Text>{images[imageIndex].title || ''}</Text>}
/>
`
