### ISSUE TITLE
Please tell me when to add the zoom function on Android. Can you add function long press picture double click restore picture scale double click enlarge picture scale

### ISSUE THREAD

**Issue by afeichuanqi** [jobtoday/react-native-image-viewing#8]
Please tell me when to add the zoom function on Android. Can you add function long press picture double click restore picture scale double click enlarge picture scale

**Comment by antonKalinin** [comment]
Zoom on Android will be released today.

**Comment by antonKalinin** [comment]
Zoom on Android released in v0.1.0
